global:
  scrape_interval: 15s
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['app:8000']
  
  - job_name: 'celery-flower'
    static_configs:
      - targets: ['celery-flower:5555']
